<?php
/**
 * @var LCB_Trustisto_Block_Index
 */
?>
<script type="text/javascript">
  (function(a,b,c,d,e,f,g,h,i){
    h=a.SPT={u:d},a.SP={init:function(a,b){h.ai=a;h.cb=b},
    go:function(){(h.eq=h.eq||[]).push(arguments)}}
    g=b.getElementsByTagName(c)[0],f=b.createElement(c),
    f.async=1,f.src="//js"+d+e,i=g.parentNode.insertBefore(f,g)
  })(window,document,"script",".trustisto.com","/socialproof.js");
  SP.init("<?php echo $this->getCode(); ?>");
</script>